test

diff --git a/.github/workflows/Terraform-Apply.yml b/.github/workflows/Terraform-Apply.yml
--- a/.github/workflows/Terraform-Apply.yml
+++ b/.github/workflows/Terraform-Apply.yml
@@ -31,6 +31,11 @@ jobs:
         #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         #     aws-region: ${{ secrets.AWS_REGION }}
+        - name: Configure AWS credentials from Test account
+          uses: aws-actions/configure-aws-credentials@v1
+          with:
+            role-to-assume: arn:aws:iam::409592171686:role/EC2-Admin
+            aws-region: us-east-1
 
         - name: Setup Terraform
           uses: hashicorp/setup-terraform@v1
@@ -48,16 +53,16 @@ jobs:
             pwd
             ls -la
         
-        - name: Terraform Plan
-          id: plan
-          if: github.event_name == 'push'
-          run: terraform plan -no-color
-          continue-on-error: true
+        # - name: Terraform Plan
+        #   id: plan
+        #   if: github.event_name == 'push'
+        #   run: terraform plan -no-color
+        #   continue-on-error: true
         
-        - name: Terraform Plan Status
-          if: steps.plan.outcome == 'failure'
-          run: exit 1
+        # - name: Terraform Plan Status
+        #   if: steps.plan.outcome == 'failure'
+        #   run: exit 1
         
-        - name: Terraform Apply
-          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-          run: terraform apply -auto-approve
+        # - name: Terraform Apply
+        #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+        #   run: terraform apply -auto-approve
